"""Tests for data/cmip6_damip_source.py (Phase 3, WP-M4.2).

Exercises data.cmip6_damip_source.CMIP6DamipSource.build_states() directly
(bypassing scripts/build_case_input.py and run_case.py, both owned by a
different/later work package -- WP-M4.3 -- per docs/plan_ph3.md §9.3's
file-ownership map) against the synthetic fixtures generated by
tests/data/damip_smoke/_make_damip_fixtures.py:

- ipsl_mini/           : full-variable hist-aer dataset -> all-ACTIVE branches
- cesm2_damip_mini/     : missing cl/clw/cli, rsdt, o3 -> SKIPPED/ANALYTIC/
                          CLIMATOLOGY branches
- o3_climatology_mini.nc: standalone O3 climatology injection source

Also covers the §6.1 decision tree's explicit o3=skip/use_model modes, the
§5.1 step-2 fail-fast month-completeness check, the required-variable
FileNotFoundError, the configs/damip_models.d + damip_experiments.yaml
loaders (including the "unknown model/experiment -> warn, don't hard-fail"
graceful-degradation path from §4.2), and one differing-target-grid case
that forces the genuine (non-identity) interp_plev_to_target path.
"""
import json
import os
import sys

import numpy as np
import pytest
from netCDF4 import Dataset

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from data import cmip6_damip_source as damip


FIXTURE_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'damip_smoke')
IPSL_RAW_DIR = os.path.join(FIXTURE_ROOT, 'ipsl_mini')
CESM2_RAW_DIR = os.path.join(FIXTURE_ROOT, 'cesm2_damip_mini')
O3_CLIMO_MINI = os.path.join(FIXTURE_ROOT, 'o3_climatology_mini.nc')

# Matches _make_damip_fixtures.py's TARGET_PLEV_HPA_TOA2SFC (identical to the
# fixtures' native plev -> interp_plev_to_target is an identity here).
TARGET_PLEV_IDENTITY = [100.0, 300.0, 500.0, 700.0, 1000.0]

# docs/input_spec.md variable lists (mirrored here, not imported from
# scripts/build_case_input.py, to keep this test independent of that file's
# ownership by a different/later work package -- WP-M4.3).
PRES_3D_VARS = ['ta_lay', 'q', 'o3', 'camt', 'cliq', 'cice', 'co2',
                'bc', 'ocphi', 'ocpho', 'sulf', 'ss', 'dust']
SURF_2D_VARS = ['ts', 'ps', 'solar', 'albedo']


def _base_cfg(raw_dir, model, experiment='hist-aer', base_years=(1850, 1851),
             warm_years=(1854, 1855), variant='r1i1p1f1', grid_label=None,
             o3='auto', o3_climatology_path=None, target_plev=None,
             case_dir=None):
    source = {
        'type': 'cmip6_damip',
        'model': model,
        'experiment': experiment,
        'raw_dir': raw_dir,
        'base_years': list(base_years),
        'warm_years': list(warm_years),
        'co2': {'source': 'constant', 'base_ppmv': 284.7, 'perturbed_ppmv': 284.7},
        'o3': o3,
        'aerosol': {'source': 'zero'},
    }
    if variant is not None:
        source['variant'] = variant
    if grid_label is not None:
        source['grid_label'] = grid_label
    if o3_climatology_path is not None:
        source['o3_climatology_path'] = o3_climatology_path
    cfg = {
        'source': source,
        'grid': {'pressure_levels': target_plev or TARGET_PLEV_IDENTITY},
    }
    if case_dir is not None:
        cfg['_case_dir'] = case_dir
    return cfg


def _assert_no_nan(state, label):
    for v in PRES_3D_VARS + SURF_2D_VARS:
        assert v in state, '%s: missing %s' % (label, v)
        arr = np.asarray(state[v])
        assert np.all(np.isfinite(arr)), '%s.%s has non-finite values' % (label, v)


# ---------------------------------------------------------------------------
# Full-variable happy path (ipsl_mini) -- all ACTIVE branches
# ---------------------------------------------------------------------------

def test_full_variable_ipsl_all_active_and_no_nan():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')

    proc = src.provenance['processes']
    assert proc['cloud']['status'] == 'ACTIVE'
    assert proc['o3']['status'] == 'MODEL'
    assert proc['solar']['status'] == 'ACTIVE'
    assert proc['flux']['status'] == 'ACTIVE'
    assert proc['albedo']['status'] == 'ACTIVE'
    assert proc['aerosol']['status'] == 'SKIPPED'

    # camt physically bounded
    assert base['camt'].min() >= 0.0 and base['camt'].max() <= 1.0
    assert warm['camt'].min() >= 0.0 and warm['camt'].max() <= 1.0


def test_full_variable_ipsl_exact_deltas():
    """ta/ts/rsdt/hfls/hfss/o3 all use per-year-constant fixture values with
    base_years=[1850,1851] / warm_years=[1854,1855] both non-leap pairs
    (gregorian) -> warm_mean - base_mean is an EXACT linear-trend multiple
    (4.0x the per-year trend), not just approximately equal (see
    _make_damip_fixtures.py's module docstring)."""
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()

    # ta trend = +0.6 K/yr, ts trend = +0.6 K/yr (same rate) -> +2.4 K
    # uniformly everywhere, INCLUDING the mountain column's HOLD/ts-filled
    # subsurface cells (ta_lay there == ts, which shifts by the same 2.4 K).
    dT = warm['ta_lay'] - base['ta_lay']
    np.testing.assert_allclose(dT, 2.4, atol=1e-8)

    # rsdt/o3 are time-invariant in the fixture -> exactly zero delta
    # (hist-aer freezes solar + this model's O3 pipeline uses the SAME
    # constant field for both periods).
    np.testing.assert_allclose(warm['solar'] - base['solar'], 0.0, atol=1e-10)
    np.testing.assert_allclose(warm['o3'] - base['o3'], 0.0, atol=1e-10)

    # albedo: rsus/rsds both time-invariant -> identical base/warm, = 40/200
    np.testing.assert_allclose(base['albedo'], 0.2, atol=1e-10)
    np.testing.assert_allclose(warm['albedo'], 0.2, atol=1e-10)

    # hfls trend +5 W/m2/yr, hfss trend +2 W/m2/yr -> Delta = 4.0x trend;
    # frc = -(warm-base) (docs/plan_ph3.md §2.5 sign law).
    np.testing.assert_allclose(nonrad['lhflx'], -20.0, atol=1e-8)
    np.testing.assert_allclose(nonrad['shflx'], -8.0, atol=1e-8)

    # cloud: aerosol-driven decline (-1%/yr trend in cl) -> warm domain mean
    # cloud fraction is lower than base (qualitative -- hybrid mass-conserving
    # projection + the mountain column's partial-layer truncation make an
    # exact closed form impractical to hand-verify here).
    assert warm['camt'].mean() < base['camt'].mean()


def test_full_variable_ipsl_sanity_checks_near_zero():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()
    sanity = src.provenance['sanity_checks']
    assert sanity['co2_equal'] is True
    assert sanity['o3_rel_diff'] < 1e-9
    assert sanity['solar_max_abs_diff_wm2'] < 1e-9


def test_provenance_json_written(tmp_path):
    case_dir = str(tmp_path / 'damip_ipsl_case')
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', case_dir=case_dir)
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()

    prov_path = os.path.join(case_dir, 'input', 'provenance.json')
    assert os.path.exists(prov_path)
    with open(prov_path) as f:
        loaded = json.load(f)
    assert loaded['model'] == 'IPSL-CM6A-LR'
    assert loaded['processes']['cloud']['status'] == 'ACTIVE'


def test_provenance_not_written_without_case_dir():
    """No `_case_dir` in cfg (e.g. a bare in-memory test cfg) -> build_states
    must not crash; it simply skips the provenance.json write."""
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    assert '_case_dir' not in cfg
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()  # must not raise


# ---------------------------------------------------------------------------
# Missing cloud / rsdt / o3 (cesm2_damip_mini) -- SKIPPED / ANALYTIC / CLIMATOLOGY
# ---------------------------------------------------------------------------

def test_missing_cloud_rsdt_o3_cesm2_climatology():
    cfg = _base_cfg(CESM2_RAW_DIR, 'CESM2', grid_label='gn', o3='auto',
                    o3_climatology_path=O3_CLIMO_MINI)
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')

    proc = src.provenance['processes']
    assert proc['cloud']['status'] == 'SKIPPED'
    assert proc['solar']['status'] == 'ANALYTIC'
    assert proc['o3']['status'] == 'CLIMATOLOGY'

    # cloud=SKIPPED -> exactly zero, both states
    for v in ('camt', 'cliq', 'cice'):
        assert np.all(base[v] == 0.0)
        assert np.all(warm[v] == 0.0)

    # solar=ANALYTIC: same lat-only function for both states -> bit-identical
    np.testing.assert_array_equal(base['solar'], warm['solar'])
    # anchors: analytic_solar output should be within a physically sane W/m2 range
    assert 0.0 < base['solar'].min()
    assert base['solar'].max() < 500.0

    # o3=CLIMATOLOGY: same injected field for both states -> bit-identical,
    # and in a physically sane kg/kg range for the mini climatology (mol/mol
    # 3e-8..5e-6 x 48/29).
    np.testing.assert_array_equal(base['o3'], warm['o3'])
    assert base['o3'].min() > 1e-9
    assert base['o3'].max() < 1e-4


def test_o3_climatology_source_missing_falls_back_to_skip_constant(monkeypatch):
    """o3=auto, no model o3, AND no climatology source resolvable at all
    (monkeypatch the module's candidate-path tuple to something that can't
    exist) -> constant 1e-12 kg/kg fallback, status SKIPPED. Guards against
    the real raw_data/ozone_*.nc file (which genuinely exists in this repo)
    accidentally satisfying the injection path in this specific test."""
    monkeypatch.setattr(damip, '_O3_CLIMATOLOGY_CANDIDATES', ('does/not/exist.nc',))
    cfg = _base_cfg(CESM2_RAW_DIR, 'CESM2', grid_label='gn', o3='auto')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()

    assert src.provenance['processes']['o3']['status'] == 'SKIPPED'
    np.testing.assert_array_equal(base['o3'], damip.O3_SKIP_CONSTANT_KGKG)
    np.testing.assert_array_equal(warm['o3'], damip.O3_SKIP_CONSTANT_KGKG)


def test_explicit_o3_skip_mode_ignores_available_model_o3():
    """ipsl_mini genuinely HAS model o3, but source.o3='skip' must still
    force the constant fallback (user-explicit skip beats availability)."""
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', o3='skip')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()

    assert src.provenance['processes']['o3']['status'] == 'SKIPPED'
    np.testing.assert_array_equal(base['o3'], damip.O3_SKIP_CONSTANT_KGKG)
    np.testing.assert_array_equal(warm['o3'], damip.O3_SKIP_CONSTANT_KGKG)


def test_explicit_o3_use_model_mode():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', o3='use_model')
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()
    assert src.provenance['processes']['o3']['status'] == 'MODEL'


def test_use_model_o3_missing_raises():
    cfg = _base_cfg(CESM2_RAW_DIR, 'CESM2', grid_label='gn', o3='use_model')
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(FileNotFoundError):
        src.build_states()


def test_invalid_o3_mode_raises():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', o3='bogus')
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(ValueError):
        src.build_states()


# ---------------------------------------------------------------------------
# Fail-fast completeness + required-variable checks (§5.1 step 2)
# ---------------------------------------------------------------------------

def test_month_completeness_fail_fast_on_missing_year():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr',
                    base_years=(1849, 1850))   # 1849 does not exist in the fixture
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(ValueError, match='1849'):
        src.build_states()


def test_required_variable_missing_raises(tmp_path):
    cfg = _base_cfg(str(tmp_path), 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(FileNotFoundError):
        src.build_states()


# ---------------------------------------------------------------------------
# configs/damip_models.d + configs/damip_experiments.yaml loaders
# ---------------------------------------------------------------------------

def test_load_model_config_known_models():
    for name in ('IPSL-CM6A-LR', 'MRI-ESM2-0', 'CESM2'):
        cfg = damip.load_model_config(name)
        assert cfg, '%s should have a models.d config' % name
        assert 'default_variant' in cfg
        assert 'default_grid' in cfg

    cesm2 = damip.load_model_config('CESM2')
    assert cesm2['vertical']['scheme'] == 'hybrid_ab_p0'
    assert 'cl' in cesm2.get('missing_ok', [])


def test_load_model_config_unknown_falls_back_with_warning(capsys):
    cfg = damip.load_model_config('SOME-MODEL-NOT-IN-REPO')
    assert cfg == {}
    captured = capsys.readouterr()
    assert 'WARNING' in captured.out


def test_list_available_models_includes_m4_trio():
    models = damip.list_available_models()
    for name in ('IPSL-CM6A-LR', 'MRI-ESM2-0', 'CESM2'):
        assert name in models


def test_load_experiment_config_known_and_unknown(capsys):
    hist_aer = damip.load_experiment_config('hist-aer')
    assert hist_aer['co2'] == 'fixed_1850'
    assert hist_aer['o3_default'] == 'auto'

    hist_strato3 = damip.load_experiment_config('hist-stratO3')
    assert hist_strato3['o3_default'] == 'use_model'

    unknown = damip.load_experiment_config('hist-not-a-real-experiment')
    assert unknown == {}
    captured = capsys.readouterr()
    assert 'WARNING' in captured.out


# ---------------------------------------------------------------------------
# Graceful model-config fallback (§4.2 "zero-yaml new model" path): variant
# and grid_label auto-discovered via glob when configs/damip_models.d has
# nothing for this model.
# ---------------------------------------------------------------------------

def test_graceful_fallback_discovers_variant_and_grid(monkeypatch):
    monkeypatch.setattr(damip, 'load_model_config', lambda name: {})
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', variant=None, grid_label=None)
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()
    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')
    # still correctly ended up ACTIVE for cloud (hybrid formula_terms
    # auto-probed with no models.d override, since vertical_cfg falls back
    # to {'scheme': 'auto'} when model_cfg == {}).
    assert src.provenance['processes']['cloud']['status'] == 'ACTIVE'
    assert src.provenance['variant'] == 'r1i1p1f1'
    assert src.provenance['grid_label'] == 'gr'


# ---------------------------------------------------------------------------
# Differing target grid -> genuine (non-identity) interp_plev_to_target path
# ---------------------------------------------------------------------------

def test_differing_target_grid_interpolates_without_crashing():
    # Extra level (600 hPa) not present in the native fixture plev -- forces
    # a real (non-identity) log-p interpolation for ta/hus/o3, and a
    # differently-shaped mass-conserving hybrid projection for cl/clw/cli.
    target = [100.0, 300.0, 500.0, 600.0, 700.0, 1000.0]
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', target_plev=target)
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')
    assert base['ta_lay'].shape[0] == len(target)
    assert base['lev'].tolist() == list(reversed(target))

    # Interpolated 600 hPa level (index 3 in sfc->TOA order, between the
    # native 500 and 700 hPa levels) must lie between the two neighboring
    # native temperatures at a non-mountain column (log-p linear interp of a
    # monotone profile stays monotone-bounded).
    lev_sfc2toa = base['lev']
    i600 = list(lev_sfc2toa).index(600.0)
    i500 = list(lev_sfc2toa).index(500.0)
    i700 = list(lev_sfc2toa).index(700.0)
    non_mountain = (1, 1)   # away from the (0,0) mountain column
    t600 = base['ta_lay'][i600][non_mountain]
    t500 = base['ta_lay'][i500][non_mountain]
    t700 = base['ta_lay'][i700][non_mountain]
    assert min(t500, t700) <= t600 <= max(t500, t700)


# ---------------------------------------------------------------------------
# hybrid_ab_p0 (CESM2-style) coefficient reading -- not exercised by
# build_states() integration tests above, because CESM2's real hist-aer
# publication has no cl/clw/cli at all (docs/plan_ph3.md §1.4), so cloud
# processing never reaches vertical-coordinate detection for that model in
# practice. Unit-test _read_hybrid_coeffs directly against a small
# CESM2-style (scalar p0 variable) fixture instead.
# ---------------------------------------------------------------------------

def test_read_hybrid_coeffs_ab_p0_convention(tmp_path):
    path = str(tmp_path / 'cl_hybrid_ab_p0.nc')
    with Dataset(path, 'w') as nc:
        nc.createDimension('lev', 3)
        lv = nc.createVariable('lev', 'f8', ('lev',))
        lv[:] = [1, 2, 3]
        lv.standard_name = 'atmosphere_hybrid_sigma_pressure_coordinate'
        lv.formula_terms = 'p0: p0 a: a b: b ps: ps'
        p0v = nc.createVariable('p0', 'f8', ())
        p0v[...] = 100000.0
        nc.createVariable('a', 'f8', ('lev',))[:] = [0.01, 0.02, 0.0]
        nc.createVariable('b', 'f8', ('lev',))[:] = [0.0, 0.3, 0.98]
        cl = nc.createVariable('cl', 'f8', ('lev',))
        cl.formula_terms = 'p0: p0 a: a b: b ps: ps'
        cl[:] = [1.0, 20.0, 40.0]

    with Dataset(path) as nc:
        formula_terms = nc.variables['cl'].formula_terms
        from data import cmip6_common as common
        vinfo = common.detect_vertical(formula_terms=formula_terms)
        assert vinfo['scheme'] == 'hybrid_ab_p0'
        a_eff, b_eff, p0_eff = damip._read_hybrid_coeffs(nc, vinfo)
        np.testing.assert_array_equal(a_eff, [0.01, 0.02, 0.0])
        np.testing.assert_array_equal(b_eff, [0.0, 0.3, 0.98])
        assert p0_eff == 100000.0

        # Feed straight into hybrid_to_plev_mass_conserving to confirm the
        # coefficients actually work end-to-end for a real (non-mocked) file.
        ps_2d = np.array([[101300.0]])
        field_hyb = np.array([1.0, 20.0, 40.0]).reshape(3, 1, 1)
        target_toa2sfc_pa = np.array([50000.0, 101300.0])
        out = common.hybrid_to_plev_mass_conserving(field_hyb, a_eff, b_eff, p0_eff, ps_2d,
                                                     target_toa2sfc_pa)
        assert out.shape == (2, 1, 1)
        assert np.all(np.isfinite(out))
