"""Tests for data/cmip6_damip_source.py (Phase 3, WP-M4.2).

Exercises data.cmip6_damip_source.CMIP6DamipSource.build_states() directly
(bypassing scripts/build_case_input.py and run_case.py, both owned by a
different/later work package -- WP-M4.3 -- per docs/plan_ph3.md §9.3's
file-ownership map) against the synthetic fixtures generated by
tests/data/damip_smoke/_make_damip_fixtures.py:

- ipsl_mini/           : full-variable hist-aer dataset -> all-ACTIVE branches
- cesm2_damip_mini/     : missing cl/clw/cli, rsdt, o3 -> SKIPPED/ANALYTIC/
                          CLIMATOLOGY branches
- o3_climatology_mini.nc: standalone O3 climatology injection source

Also covers the §6.1 decision tree's explicit o3=skip/use_model modes, the
§5.1 step-2 fail-fast month-completeness check, the required-variable
FileNotFoundError, the configs/damip_models.d + damip_experiments.yaml
loaders (including the "unknown model/experiment -> warn, don't hard-fail"
graceful-degradation path from §4.2), and one differing-target-grid case
that forces the genuine (non-identity) interp_plev_to_target path.
"""
import glob
import json
import os
import sys

import numpy as np
import pytest
from netCDF4 import Dataset

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from data import cmip6_damip_source as damip


FIXTURE_ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'data', 'damip_smoke')
IPSL_RAW_DIR = os.path.join(FIXTURE_ROOT, 'ipsl_mini')
CESM2_RAW_DIR = os.path.join(FIXTURE_ROOT, 'cesm2_damip_mini')
O3_CLIMO_MINI = os.path.join(FIXTURE_ROOT, 'o3_climatology_mini.nc')

# Matches _make_damip_fixtures.py's TARGET_PLEV_HPA_TOA2SFC (identical to the
# fixtures' native plev -> interp_plev_to_target is an identity here).
TARGET_PLEV_IDENTITY = [100.0, 300.0, 500.0, 700.0, 1000.0]

# docs/input_spec.md variable lists (mirrored here, not imported from
# scripts/build_case_input.py, to keep this test independent of that file's
# ownership by a different/later work package -- WP-M4.3).
PRES_3D_VARS = ['ta_lay', 'q', 'o3', 'camt', 'cliq', 'cice', 'co2',
                'bc', 'ocphi', 'ocpho', 'sulf', 'ss', 'dust']
SURF_2D_VARS = ['ts', 'ps', 'solar', 'albedo']


def _base_cfg(raw_dir, model, experiment='hist-aer', base_years=(1850, 1851),
             warm_years=(1854, 1855), variant='r1i1p1f1', grid_label=None,
             o3='auto', o3_climatology_path=None, target_plev=None,
             case_dir=None):
    source = {
        'type': 'cmip6_damip',
        'model': model,
        'experiment': experiment,
        'raw_dir': raw_dir,
        'base_years': list(base_years),
        'warm_years': list(warm_years),
        'co2': {'source': 'constant', 'base_ppmv': 284.7, 'perturbed_ppmv': 284.7},
        'o3': o3,
        'aerosol': {'source': 'zero'},
    }
    if variant is not None:
        source['variant'] = variant
    if grid_label is not None:
        source['grid_label'] = grid_label
    if o3_climatology_path is not None:
        source['o3_climatology_path'] = o3_climatology_path
    cfg = {
        'source': source,
        'grid': {'pressure_levels': target_plev or TARGET_PLEV_IDENTITY},
    }
    if case_dir is not None:
        cfg['_case_dir'] = case_dir
    return cfg


def _assert_no_nan(state, label):
    for v in PRES_3D_VARS + SURF_2D_VARS:
        assert v in state, '%s: missing %s' % (label, v)
        arr = np.asarray(state[v])
        assert np.all(np.isfinite(arr)), '%s.%s has non-finite values' % (label, v)


# ---------------------------------------------------------------------------
# Full-variable happy path (ipsl_mini) -- all ACTIVE branches
# ---------------------------------------------------------------------------

def test_full_variable_ipsl_all_active_and_no_nan():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')

    proc = src.provenance['processes']
    assert proc['cloud']['status'] == 'ACTIVE'
    assert proc['o3']['status'] == 'MODEL'
    assert proc['solar']['status'] == 'ACTIVE'
    assert proc['flux']['status'] == 'ACTIVE'
    assert proc['albedo']['status'] == 'ACTIVE'
    assert proc['aerosol']['status'] == 'SKIPPED'

    # camt physically bounded
    assert base['camt'].min() >= 0.0 and base['camt'].max() <= 1.0
    assert warm['camt'].min() >= 0.0 and warm['camt'].max() <= 1.0


def _copy_fixture(src_dir, dst_dir, flip_lat=False):
    """Copy a fixture raw_dir, optionally publishing it N->S instead of S->N.

    Also overwrites hfls/hfss with a field whose warm-minus-base difference
    varies with latitude. The stock fixture's surface fluxes are
    latitude-uniform, which makes a latitude flip invisible in the derived
    nonrad forcing -- a test built on them passes whether or not the code
    under test is correct.

    Fixture time axis is 72 months = 1850-01..1855-12, so
    ``year = 1850 + t // 12``; the pattern is zero in the base years and
    lat/lon-dependent in the warm years, giving nonrad = -(warm - base) an
    unambiguous latitudinal signature.
    """
    from netCDF4 import Dataset as _DS
    os.makedirs(dst_dir, exist_ok=True)
    for src_path in sorted(glob.glob(os.path.join(src_dir, '*.nc'))):
        base_name = os.path.basename(src_path)
        dst_path = os.path.join(dst_dir, base_name)
        varname = base_name.split('_')[0]
        with _DS(src_path) as src, _DS(dst_path, 'w', format='NETCDF4') as dst:
            for dname, dim in src.dimensions.items():
                dst.createDimension(dname, dim.size)
            for vname, var in src.variables.items():
                out = dst.createVariable(vname, var.datatype, var.dimensions)
                out.setncatts({k: var.getncattr(k) for k in var.ncattrs()
                               if k != '_FillValue'})
                data = np.array(var[:])
                if vname == varname and varname in ('hfls', 'hfss'):
                    nt, nlat, nlon = data.shape
                    jj, ii = np.meshgrid(np.arange(nlat), np.arange(nlon), indexing='ij')
                    pattern = 10.0 * jj + 3.0 * ii
                    warm = (1850 + np.arange(nt) // 12) >= 1854
                    data = 100.0 + pattern[None, :, :] * warm[:, None, None]
                if 'lat' in var.dimensions and flip_lat:
                    data = np.flip(data, axis=var.dimensions.index('lat'))
                out[:] = data
            dst.setncatts({k: src.getncattr(k) for k in src.ncattrs()})
    return dst_dir


def test_nonrad_forcing_is_grid_normalized_like_every_other_field(tmp_path):
    """Regression test: lhflx/shflx must go through the same normalize_grid
    permutation as the state fields.

    build_states() normalized every array in base_state/warm_state but left
    the `nonrad` dict on the raw file ordering. scripts/build_case_input.py's
    write_nonrad_nc() then writes those arrays against base_state's
    *normalized* lat/lon axes -- so for a model published N->S the surface
    latent/sensible heat forcing would land mirrored in latitude relative to
    every other field, with nothing raising an error.

    All nine models validated in M4/M5 happen to publish lat S->N and lon
    0-360 ascending (verified against the downloaded ESGF files), which is
    why no shipped run carries a wrong number -- the defect was latent. This
    test makes it non-latent by building the same case twice, once from a
    lat-flipped copy of the fixture.
    """
    ref_dir = _copy_fixture(IPSL_RAW_DIR, str(tmp_path / 'ipsl_sn'), flip_lat=False)
    ref_cfg = _base_cfg(ref_dir, 'IPSL-CM6A-LR', grid_label='gr')
    ref_base, _ref_warm, ref_nonrad = damip.CMIP6DamipSource(ref_cfg).build_states()

    flipped_dir = _copy_fixture(IPSL_RAW_DIR, str(tmp_path / 'ipsl_ns'), flip_lat=True)
    flip_cfg = _base_cfg(flipped_dir, 'IPSL-CM6A-LR', grid_label='gr')
    flip_base, _flip_warm, flip_nonrad = damip.CMIP6DamipSource(flip_cfg).build_states()

    # The forcing must actually vary with latitude, or a flip is invisible
    # and this test would pass against the buggy code too.
    assert np.ptp(ref_nonrad['lhflx'], axis=0).max() > 0.0

    # Sanity: the flipped fixture really is a different file ordering that
    # normalize_grid had to undo (otherwise this test proves nothing).
    with Dataset(sorted(glob.glob(os.path.join(flipped_dir, 'ta_*.nc')))[0]) as d:
        raw_lat = np.array(d.variables['lat'][:])
    assert raw_lat[0] > raw_lat[-1], 'fixture copy should be published N->S'

    # Both builds must land on the same normalized (S->N) latitude axis...
    np.testing.assert_array_equal(ref_base['lat'], flip_base['lat'])
    assert np.all(np.diff(flip_base['lat']) > 0)

    # ...and every field, state AND non-radiative forcing, must agree.
    np.testing.assert_allclose(flip_base['ts'], ref_base['ts'], rtol=0, atol=0)
    for key in ('lhflx', 'shflx'):
        np.testing.assert_allclose(
            flip_nonrad[key], ref_nonrad[key], rtol=0, atol=0,
            err_msg='nonrad[%r] not normalized with the rest of the state' % key)


def test_cloud_degrades_gracefully_on_unsupported_vertical_coordinate(monkeypatch):
    """Regression test for a real bug hit building damip_hadgem3_histaer:
    HadGEM3-GC31-LL's cl uses a hybrid-HEIGHT coordinate
    ("a: lev b: b orog: orog", z = a + b*orog) rather than hybrid-sigma-
    PRESSURE -- cmip6_common.detect_vertical raises ValueError for a
    formula_terms string it doesn't recognize. Supporting hybrid-height
    would need a genuinely different physical conversion, out of scope per
    plan §3/R4 ("framework enhancement", not a per-model config fix) --
    the correct behavior is to degrade to cloud=SKIPPED, not crash the
    whole case build. Monkeypatch detect_vertical to force the ValueError
    (the real failure mode) rather than constructing a whole new
    hybrid-height fixture -- this tests the exception-handling path
    directly, independent of detect_vertical's own (separately tested)
    format-recognition logic.
    """
    def raise_unrecognized(*args, **kwargs):
        raise ValueError("detect_vertical: unrecognized formula_terms 'a: lev b: b orog: orog'")

    monkeypatch.setattr(damip.common, 'detect_vertical', raise_unrecognized)

    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()  # must not raise

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')

    proc = src.provenance['processes']
    assert proc['cloud']['status'] == 'SKIPPED'
    assert 'vertical coordinate unsupported' in proc['cloud']['reason']
    assert np.all(base['camt'] == 0.0)
    assert np.all(base['cliq'] == 0.0)
    assert np.all(base['cice'] == 0.0)

    # Other processes (o3, solar, flux, albedo) must be unaffected -- only
    # cloud degrades.
    assert proc['o3']['status'] == 'MODEL'
    assert proc['solar']['status'] == 'ACTIVE'
    assert proc['flux']['status'] == 'ACTIVE'


def test_full_variable_ipsl_exact_deltas():
    """ta/ts/rsdt/hfls/hfss/o3 all use per-year-constant fixture values with
    base_years=[1850,1851] / warm_years=[1854,1855] both non-leap pairs
    (gregorian) -> warm_mean - base_mean is an EXACT linear-trend multiple
    (4.0x the per-year trend), not just approximately equal (see
    _make_damip_fixtures.py's module docstring)."""
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()

    # ta trend = +0.6 K/yr, ts trend = +0.6 K/yr (same rate) -> +2.4 K
    # uniformly everywhere, INCLUDING the mountain column's HOLD/ts-filled
    # subsurface cells (ta_lay there == ts, which shifts by the same 2.4 K).
    dT = warm['ta_lay'] - base['ta_lay']
    np.testing.assert_allclose(dT, 2.4, atol=1e-8)

    # rsdt/o3 are time-invariant in the fixture -> exactly zero delta
    # (hist-aer freezes solar + this model's O3 pipeline uses the SAME
    # constant field for both periods).
    np.testing.assert_allclose(warm['solar'] - base['solar'], 0.0, atol=1e-10)
    np.testing.assert_allclose(warm['o3'] - base['o3'], 0.0, atol=1e-10)

    # albedo: rsus/rsds both time-invariant -> identical base/warm, = 40/200
    np.testing.assert_allclose(base['albedo'], 0.2, atol=1e-10)
    np.testing.assert_allclose(warm['albedo'], 0.2, atol=1e-10)

    # hfls trend +5 W/m2/yr, hfss trend +2 W/m2/yr -> Delta = 4.0x trend;
    # frc = -(warm-base) (docs/plan_ph3.md §2.5 sign law).
    np.testing.assert_allclose(nonrad['lhflx'], -20.0, atol=1e-8)
    np.testing.assert_allclose(nonrad['shflx'], -8.0, atol=1e-8)

    # cloud: aerosol-driven decline (-1%/yr trend in cl) -> warm domain mean
    # cloud fraction is lower than base (qualitative -- hybrid mass-conserving
    # projection + the mountain column's partial-layer truncation make an
    # exact closed form impractical to hand-verify here).
    assert warm['camt'].mean() < base['camt'].mean()


def test_full_variable_ipsl_sanity_checks_near_zero():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()
    sanity = src.provenance['sanity_checks']
    assert sanity['co2_equal'] is True
    assert sanity['o3_rel_diff'] < 1e-9
    assert sanity['solar_max_abs_diff_wm2'] < 1e-9


def test_provenance_json_written(tmp_path):
    case_dir = str(tmp_path / 'damip_ipsl_case')
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', case_dir=case_dir)
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()

    prov_path = os.path.join(case_dir, 'input', 'provenance.json')
    assert os.path.exists(prov_path)
    with open(prov_path) as f:
        loaded = json.load(f)
    assert loaded['model'] == 'IPSL-CM6A-LR'
    assert loaded['processes']['cloud']['status'] == 'ACTIVE'


def test_provenance_not_written_without_case_dir():
    """No `_case_dir` in cfg (e.g. a bare in-memory test cfg) -> build_states
    must not crash; it simply skips the provenance.json write."""
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr')
    assert '_case_dir' not in cfg
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()  # must not raise


# ---------------------------------------------------------------------------
# Missing cloud / rsdt / o3 (cesm2_damip_mini) -- SKIPPED / ANALYTIC / CLIMATOLOGY
# ---------------------------------------------------------------------------

def test_missing_cloud_rsdt_o3_cesm2_climatology():
    cfg = _base_cfg(CESM2_RAW_DIR, 'CESM2', grid_label='gn', o3='auto',
                    o3_climatology_path=O3_CLIMO_MINI)
    src = damip.CMIP6DamipSource(cfg)
    base, warm, nonrad = src.build_states()

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')

    proc = src.provenance['processes']
    assert proc['cloud']['status'] == 'SKIPPED'
    assert proc['solar']['status'] == 'ANALYTIC'
    assert proc['o3']['status'] == 'CLIMATOLOGY'

    # cloud=SKIPPED -> exactly zero, both states
    for v in ('camt', 'cliq', 'cice'):
        assert np.all(base[v] == 0.0)
        assert np.all(warm[v] == 0.0)

    # solar=ANALYTIC: same lat-only function for both states -> bit-identical
    np.testing.assert_array_equal(base['solar'], warm['solar'])
    # anchors: analytic_solar output should be within a physically sane W/m2 range
    assert 0.0 < base['solar'].min()
    assert base['solar'].max() < 500.0

    # o3=CLIMATOLOGY: same injected field for both states -> bit-identical,
    # and in a physically sane kg/kg range for the mini climatology (mol/mol
    # 3e-8..5e-6 x 48/29).
    np.testing.assert_array_equal(base['o3'], warm['o3'])
    assert base['o3'].min() > 1e-9
    assert base['o3'].max() < 1e-4


def test_o3_climatology_source_missing_falls_back_to_skip_constant(monkeypatch):
    """o3=auto, no model o3, AND no climatology source resolvable at all
    (monkeypatch the module's candidate-path tuple to something that can't
    exist) -> constant 1e-12 kg/kg fallback, status SKIPPED. Guards against
    the real raw_data/ozone_*.nc file (which genuinely exists in this repo)
    accidentally satisfying the injection path in this specific test."""
    monkeypatch.setattr(damip, '_O3_CLIMATOLOGY_CANDIDATES', ('does/not/exist.nc',))
    cfg = _base_cfg(CESM2_RAW_DIR, 'CESM2', grid_label='gn', o3='auto')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()

    assert src.provenance['processes']['o3']['status'] == 'SKIPPED'
    np.testing.assert_array_equal(base['o3'], damip.O3_SKIP_CONSTANT_KGKG)
    np.testing.assert_array_equal(warm['o3'], damip.O3_SKIP_CONSTANT_KGKG)


def test_explicit_o3_skip_mode_ignores_available_model_o3():
    """ipsl_mini genuinely HAS model o3, but source.o3='skip' must still
    force the constant fallback (user-explicit skip beats availability)."""
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', o3='skip')
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()

    assert src.provenance['processes']['o3']['status'] == 'SKIPPED'
    np.testing.assert_array_equal(base['o3'], damip.O3_SKIP_CONSTANT_KGKG)
    np.testing.assert_array_equal(warm['o3'], damip.O3_SKIP_CONSTANT_KGKG)


def test_explicit_o3_use_model_mode():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', o3='use_model')
    src = damip.CMIP6DamipSource(cfg)
    src.build_states()
    assert src.provenance['processes']['o3']['status'] == 'MODEL'


def test_use_model_o3_missing_raises():
    cfg = _base_cfg(CESM2_RAW_DIR, 'CESM2', grid_label='gn', o3='use_model')
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(FileNotFoundError):
        src.build_states()


def test_invalid_o3_mode_raises():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', o3='bogus')
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(ValueError):
        src.build_states()


# ---------------------------------------------------------------------------
# Fail-fast completeness + required-variable checks (§5.1 step 2)
# ---------------------------------------------------------------------------

def test_month_completeness_fail_fast_on_missing_year():
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr',
                    base_years=(1849, 1850))   # 1849 does not exist in the fixture
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(ValueError, match='1849'):
        src.build_states()


def test_required_variable_missing_raises(tmp_path):
    cfg = _base_cfg(str(tmp_path), 'IPSL-CM6A-LR', grid_label='gr')
    src = damip.CMIP6DamipSource(cfg)
    with pytest.raises(FileNotFoundError):
        src.build_states()


# ---------------------------------------------------------------------------
# configs/damip_models.d + configs/damip_experiments.yaml loaders
# ---------------------------------------------------------------------------

def test_load_model_config_known_models():
    for name in ('IPSL-CM6A-LR', 'MRI-ESM2-0', 'CESM2'):
        cfg = damip.load_model_config(name)
        assert cfg, '%s should have a models.d config' % name
        assert 'default_variant' in cfg
        assert 'default_grid' in cfg

    cesm2 = damip.load_model_config('CESM2')
    assert cesm2['vertical']['scheme'] == 'hybrid_ab_p0'
    assert 'cl' in cesm2.get('missing_ok', [])


def test_load_model_config_unknown_falls_back_with_warning(capsys):
    cfg = damip.load_model_config('SOME-MODEL-NOT-IN-REPO')
    assert cfg == {}
    captured = capsys.readouterr()
    assert 'WARNING' in captured.out


def test_list_available_models_includes_m4_trio():
    models = damip.list_available_models()
    for name in ('IPSL-CM6A-LR', 'MRI-ESM2-0', 'CESM2'):
        assert name in models


def test_load_experiment_config_known_and_unknown(capsys):
    hist_aer = damip.load_experiment_config('hist-aer')
    assert hist_aer['co2'] == 'fixed_1850'
    assert hist_aer['o3_default'] == 'auto'

    hist_strato3 = damip.load_experiment_config('hist-stratO3')
    assert hist_strato3['o3_default'] == 'use_model'

    unknown = damip.load_experiment_config('hist-not-a-real-experiment')
    assert unknown == {}
    captured = capsys.readouterr()
    assert 'WARNING' in captured.out


# ---------------------------------------------------------------------------
# Graceful model-config fallback (§4.2 "zero-yaml new model" path): variant
# and grid_label auto-discovered via glob when configs/damip_models.d has
# nothing for this model.
# ---------------------------------------------------------------------------

def test_graceful_fallback_discovers_variant_and_grid(monkeypatch):
    monkeypatch.setattr(damip, 'load_model_config', lambda name: {})
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', variant=None, grid_label=None)
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()
    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')
    # still correctly ended up ACTIVE for cloud (hybrid formula_terms
    # auto-probed with no models.d override, since vertical_cfg falls back
    # to {'scheme': 'auto'} when model_cfg == {}).
    assert src.provenance['processes']['cloud']['status'] == 'ACTIVE'
    assert src.provenance['variant'] == 'r1i1p1f1'
    assert src.provenance['grid_label'] == 'gr'


# ---------------------------------------------------------------------------
# Differing target grid -> genuine (non-identity) interp_plev_to_target path
# ---------------------------------------------------------------------------

def test_differing_target_grid_interpolates_without_crashing():
    # Extra level (600 hPa) not present in the native fixture plev -- forces
    # a real (non-identity) log-p interpolation for ta/hus/o3, and a
    # differently-shaped mass-conserving hybrid projection for cl/clw/cli.
    target = [100.0, 300.0, 500.0, 600.0, 700.0, 1000.0]
    cfg = _base_cfg(IPSL_RAW_DIR, 'IPSL-CM6A-LR', grid_label='gr', target_plev=target)
    src = damip.CMIP6DamipSource(cfg)
    base, warm, _ = src.build_states()

    _assert_no_nan(base, 'base')
    _assert_no_nan(warm, 'warm')
    assert base['ta_lay'].shape[0] == len(target)
    assert base['lev'].tolist() == list(reversed(target))

    # Interpolated 600 hPa level (index 3 in sfc->TOA order, between the
    # native 500 and 700 hPa levels) must lie between the two neighboring
    # native temperatures at a non-mountain column (log-p linear interp of a
    # monotone profile stays monotone-bounded).
    lev_sfc2toa = base['lev']
    i600 = list(lev_sfc2toa).index(600.0)
    i500 = list(lev_sfc2toa).index(500.0)
    i700 = list(lev_sfc2toa).index(700.0)
    non_mountain = (1, 1)   # away from the (0,0) mountain column
    t600 = base['ta_lay'][i600][non_mountain]
    t500 = base['ta_lay'][i500][non_mountain]
    t700 = base['ta_lay'][i700][non_mountain]
    assert min(t500, t700) <= t600 <= max(t500, t700)


# ---------------------------------------------------------------------------
# hybrid_ab_p0 (CESM2-style) coefficient reading -- not exercised by
# build_states() integration tests above, because CESM2's real hist-aer
# publication has no cl/clw/cli at all (docs/plan_ph3.md §1.4), so cloud
# processing never reaches vertical-coordinate detection for that model in
# practice. Unit-test _read_hybrid_coeffs directly against a small
# CESM2-style (scalar p0 variable) fixture instead.
# ---------------------------------------------------------------------------

def test_read_hybrid_coeffs_ab_p0_convention(tmp_path):
    path = str(tmp_path / 'cl_hybrid_ab_p0.nc')
    with Dataset(path, 'w') as nc:
        nc.createDimension('lev', 3)
        lv = nc.createVariable('lev', 'f8', ('lev',))
        lv[:] = [1, 2, 3]
        lv.standard_name = 'atmosphere_hybrid_sigma_pressure_coordinate'
        lv.formula_terms = 'p0: p0 a: a b: b ps: ps'
        p0v = nc.createVariable('p0', 'f8', ())
        p0v[...] = 100000.0
        nc.createVariable('a', 'f8', ('lev',))[:] = [0.01, 0.02, 0.0]
        nc.createVariable('b', 'f8', ('lev',))[:] = [0.0, 0.3, 0.98]
        cl = nc.createVariable('cl', 'f8', ('lev',))
        cl.formula_terms = 'p0: p0 a: a b: b ps: ps'
        cl[:] = [1.0, 20.0, 40.0]

    with Dataset(path) as nc:
        formula_terms = nc.variables['cl'].formula_terms
        from data import cmip6_common as common
        vinfo = common.detect_vertical(formula_terms=formula_terms)
        assert vinfo['scheme'] == 'hybrid_ab_p0'
        a_eff, b_eff, p0_eff, flipped = damip._read_hybrid_coeffs(nc, vinfo)
        # b ascends 0.0->0.98 (TOA->sfc already, CESM2's native convention) -> no flip.
        assert flipped is False
        np.testing.assert_array_equal(a_eff, [0.01, 0.02, 0.0])
        np.testing.assert_array_equal(b_eff, [0.0, 0.3, 0.98])
        assert p0_eff == 100000.0

        # Feed straight into hybrid_to_plev_mass_conserving to confirm the
        # coefficients actually work end-to-end for a real (non-mocked) file.
        ps_2d = np.array([[101300.0]])
        field_hyb = np.array([1.0, 20.0, 40.0]).reshape(3, 1, 1)
        target_toa2sfc_pa = np.array([50000.0, 101300.0])
        out = common.hybrid_to_plev_mass_conserving(field_hyb, a_eff, b_eff, p0_eff, ps_2d,
                                                     target_toa2sfc_pa)
        assert out.shape == (2, 1, 1)
        assert np.all(np.isfinite(out))


def test_read_hybrid_coeffs_ap_b_interface_convention_averaged_to_midlayer(tmp_path):
    """Regression test for a real bug hit against actual downloaded
    IPSL-CM6A-LR hist-aer data (WP-M4.5): IPSL's ap/b are published on a
    dim (`klevp1`, "levels + 1") one longer than the field's own level
    dimension (`presnivs`) -- interface/boundary pressures, not midpoint
    pressures. Feeding them straight into hybrid_to_plev_mass_conserving
    (which requires a/b the same length as the field) crashed with
    IndexError. _read_hybrid_coeffs must detect the +1 length and average
    adjacent interface pairs down to nlev_data midpoint values.
    """
    path = str(tmp_path / 'cl_hybrid_ap_b_interface.nc')
    with Dataset(path, 'w') as nc:
        nc.createDimension('presnivs', 3)
        nc.createDimension('klevp1', 4)
        nc.createVariable('presnivs', 'f8', ('presnivs',))[:] = [1, 2, 3]
        # Interface coefficients (4 boundaries framing 3 layers), TOA->sfc
        # order (b ascending 0->1) so this test isolates interface-averaging
        # from the separate order-flip behavior (see the dedicated flip test
        # below, which uses IPSL's real sfc->TOA direction).
        ap_iface = [10000.0, 6000.0, 2000.0, 0.0]
        b_iface = [0.0, 0.2, 0.6, 1.0]
        nc.createVariable('ap', 'f8', ('klevp1',))[:] = ap_iface
        nc.createVariable('b', 'f8', ('klevp1',))[:] = b_iface
        cl = nc.createVariable('cl', 'f8', ('presnivs',))
        cl[:] = [1.0, 20.0, 40.0]

    with Dataset(path) as nc:
        from data import cmip6_common as common
        vinfo = {'scheme': 'hybrid_ap_b', 'ap': 'ap', 'b': 'b'}  # explicit override, no formula_terms
        nlev_data = nc.variables['cl'].shape[0]
        assert nlev_data == 3
        a_eff, b_eff, p0_eff, flipped = damip._read_hybrid_coeffs(nc, vinfo, nlev_data=nlev_data)

        # Exact pairwise average of the 4 interface values -> 3 midlayer values.
        # Already TOA->sfc (b ascending) -> no flip.
        assert flipped is False
        np.testing.assert_array_almost_equal(a_eff, [8000.0, 4000.0, 1000.0])
        np.testing.assert_array_almost_equal(b_eff, [0.1, 0.4, 0.8])
        assert p0_eff == 1.0  # hybrid_ap_b convention: p = ap*1 + b*ps

        # Feed into hybrid_to_plev_mass_conserving -- must NOT raise IndexError
        # (this is the exact call sequence that crashed against real IPSL data).
        ps_2d = np.array([[101300.0]])
        field_hyb = np.array([1.0, 20.0, 40.0]).reshape(3, 1, 1)
        target_toa2sfc_pa = np.array([50000.0, 101300.0])
        out = common.hybrid_to_plev_mass_conserving(field_hyb, a_eff, b_eff, p0_eff, ps_2d,
                                                     target_toa2sfc_pa)
        assert out.shape == (2, 1, 1)
        assert np.all(np.isfinite(out))


def test_read_hybrid_coeffs_sfc_to_toa_order_detected_and_flipped(tmp_path):
    """Regression test for a real bug hit against actual downloaded
    IPSL-CM6A-LR hist-aer data (WP-M4.5), found AFTER the interface-averaging
    fix above by sanity-checking output cloud fractions against the raw
    input's actual magnitude (build succeeded but produced near-zero camt/
    cliq/cice everywhere, despite raw cl having mean=8.4%, max=97.9%).

    IPSL stores hybrid levels surface->TOA (confirmed: its `presnivs`
    diagnostic coordinate runs ~1012 hPa at index 0 down to ~1.5 Pa at the
    last index; its raw ap/b interface arrays likewise have b descending
    from 1.0 toward 0.0). hybrid_to_plev_mass_conserving's only prior use
    (CESM2) is TOA->sfc, and the calling code silently assumed that
    direction for every model without checking. _read_hybrid_coeffs must
    detect the direction from b and reverse the coefficients (reporting
    `flipped=True` so the caller also reverses the field data the same way
    -- reversing only one side scrambles the profile without erroring).
    """
    path = str(tmp_path / 'cl_hybrid_sfc_to_toa.nc')
    with Dataset(path, 'w') as nc:
        nc.createDimension('presnivs', 3)
        nc.createDimension('klevp1', 4)
        nc.createVariable('presnivs', 'f8', ('presnivs',))[:] = [101200, 50000, 5]
        # Interface coefficients in IPSL's real sfc->TOA direction: b
        # descends from 1.0 (surface) to 0.0 (TOA).
        ap_iface = [0.0, 2000.0, 6000.0, 10000.0]
        b_iface = [1.0, 0.6, 0.2, 0.0]
        nc.createVariable('ap', 'f8', ('klevp1',))[:] = ap_iface
        nc.createVariable('b', 'f8', ('klevp1',))[:] = b_iface
        # Field data ALSO stored sfc->TOA to match: large near-surface
        # (index 0), ~0 near TOA (index -1) -- like real cloud fraction.
        nc.createVariable('cl', 'f8', ('presnivs',))[:] = [40.0, 20.0, 1.0]

    with Dataset(path) as nc:
        from data import cmip6_common as common
        vinfo = {'scheme': 'hybrid_ap_b', 'ap': 'ap', 'b': 'b'}
        a_eff, b_eff, p0_eff, flipped = damip._read_hybrid_coeffs(nc, vinfo, nlev_data=3)

        assert flipped is True
        # Midlayer average of the (still sfc->TOA) interface values is
        # [0.8, 0.4, 0.1] for b (matching the ascending-b test above's
        # midlayer numbers, just not yet reversed) -- after the flip it must
        # come out reversed and ascending (TOA->sfc): b_eff[0] < b_eff[-1].
        np.testing.assert_array_almost_equal(b_eff, [0.1, 0.4, 0.8])
        assert b_eff[0] < b_eff[-1]

        # The caller must reverse the field the same way; simulate that here
        # and confirm the mass-conserving projection produces a physically
        # sane (not near-zero-everywhere) result concentrated near the
        # surface, matching the input's actual near-surface concentration.
        cl_native = np.array([40.0, 20.0, 1.0]).reshape(3, 1, 1)
        cl_toa2sfc = cl_native[::-1] if flipped else cl_native
        ps_2d = np.array([[101300.0]])
        # Last level well below ps (not equal to it) so the final target
        # layer [70000, ps] has genuine width and can capture the
        # near-surface (~820 hPa) hybrid layer where cl_native's 40.0 lives.
        target_toa2sfc_pa = np.array([5000.0, 70000.0])
        out = common.hybrid_to_plev_mass_conserving(cl_toa2sfc, a_eff, b_eff, p0_eff, ps_2d,
                                                     target_toa2sfc_pa)
        assert np.all(np.isfinite(out))
        # Surface-adjacent target layer must retain a substantial (not
        # near-zero) fraction of the input's near-surface cloud amount.
        assert out[-1, 0, 0] > 5.0


def test_read_hybrid_coeffs_ab_p0_matching_length_not_averaged(tmp_path):
    """When the raw coefficient array already matches nlev_data (CESM2's
    real case: hyam/hybm are mid-layer, same length as the field), passing
    nlev_data must NOT trigger interface-averaging -- values pass through
    unchanged. This guards the CESM2 regression gold: WP-M4.1's bit-exact
    md5 match against real CESM2 raw data must not be perturbed by this fix.
    """
    path = str(tmp_path / 'cl_hybrid_ab_p0_matching.nc')
    with Dataset(path, 'w') as nc:
        nc.createDimension('lev', 3)
        nc.createVariable('lev', 'f8', ('lev',))[:] = [1, 2, 3]
        p0v = nc.createVariable('p0', 'f8', ())
        p0v[...] = 100000.0
        nc.createVariable('a', 'f8', ('lev',))[:] = [0.01, 0.02, 0.0]
        nc.createVariable('b', 'f8', ('lev',))[:] = [0.0, 0.3, 0.98]
        nc.createVariable('cl', 'f8', ('lev',))[:] = [1.0, 20.0, 40.0]

    with Dataset(path) as nc:
        vinfo = {'scheme': 'hybrid_ab_p0', 'a': 'a', 'b': 'b', 'p0': 'p0'}
        a_eff, b_eff, p0_eff, flipped = damip._read_hybrid_coeffs(nc, vinfo, nlev_data=3)
        assert flipped is False
        np.testing.assert_array_equal(a_eff, [0.01, 0.02, 0.0])
        np.testing.assert_array_equal(b_eff, [0.0, 0.3, 0.98])
